# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MiltiDB(object):
    def setupUi(self, MiltiDB):
        MiltiDB.setObjectName("MiltiDB")
        MiltiDB.resize(876, 898)
        self.centralwidget = QtWidgets.QWidget(MiltiDB)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutLeft = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutLeft.setMinimumSize(QtCore.QSize(350, 0))
        self.verticalLayoutLeft.setMaximumSize(QtCore.QSize(350, 16777215))
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutLeft)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelQueryEditor = QtWidgets.QLabel(self.verticalLayoutLeft)
        self.labelQueryEditor.setEnabled(True)
        self.labelQueryEditor.setMinimumSize(QtCore.QSize(350, 30))
        self.labelQueryEditor.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelQueryEditor.setFont(font)
        self.labelQueryEditor.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelQueryEditor.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelQueryEditor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQueryEditor.setObjectName("labelQueryEditor")
        self.verticalLayout_3.addWidget(self.labelQueryEditor)
        self.queryEditor = QtWidgets.QPlainTextEdit(self.verticalLayoutLeft)
        self.queryEditor.setMinimumSize(QtCore.QSize(350, 0))
        self.queryEditor.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queryEditor.setFont(font)
        self.queryEditor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.queryEditor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.queryEditor.setPlainText("")
        self.queryEditor.setObjectName("queryEditor")
        self.verticalLayout_3.addWidget(self.queryEditor)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.runQuery = QtWidgets.QPushButton(self.verticalLayoutLeft)
        self.runQuery.setMinimumSize(QtCore.QSize(100, 40))
        self.runQuery.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.runQuery.setFont(font)
        self.runQuery.setObjectName("runQuery")
        self.horizontalLayout_2.addWidget(self.runQuery)
        self.saveResult = QtWidgets.QPushButton(self.verticalLayoutLeft)
        self.saveResult.setMinimumSize(QtCore.QSize(220, 40))
        self.saveResult.setMaximumSize(QtCore.QSize(220, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveResult.setFont(font)
        self.saveResult.setObjectName("saveResult")
        self.horizontalLayout_2.addWidget(self.saveResult)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.verticalLayoutLeft)
        self.verticalLayoutRight = QtWidgets.QVBoxLayout()
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")
        self.labelLogInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelLogInfo.setMinimumSize(QtCore.QSize(500, 30))
        self.labelLogInfo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelLogInfo.setFont(font)
        self.labelLogInfo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelLogInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelLogInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogInfo.setObjectName("labelLogInfo")
        self.verticalLayoutRight.addWidget(self.labelLogInfo)
        self.logInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.logInfo.setMinimumSize(QtCore.QSize(500, 300))
        self.logInfo.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.logInfo.setFont(font)
        self.logInfo.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.logInfo.setObjectName("logInfo")
        self.verticalLayoutRight.addWidget(self.logInfo)
        self.labelQueryResult = QtWidgets.QLabel(self.centralwidget)
        self.labelQueryResult.setMinimumSize(QtCore.QSize(500, 30))
        self.labelQueryResult.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelQueryResult.setFont(font)
        self.labelQueryResult.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelQueryResult.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelQueryResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQueryResult.setObjectName("labelQueryResult")
        self.verticalLayoutRight.addWidget(self.labelQueryResult)
        self.queryResult = QtWidgets.QTableView(self.centralwidget)
        self.queryResult.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.queryResult.setFont(font)
        self.queryResult.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.queryResult.setObjectName("queryResult")
        self.verticalLayoutRight.addWidget(self.queryResult)
        self.horizontalLayout.addLayout(self.verticalLayoutRight)
        MiltiDB.setCentralWidget(self.centralwidget)

        self.retranslateUi(MiltiDB)
        QtCore.QMetaObject.connectSlotsByName(MiltiDB)

    def retranslateUi(self, MiltiDB):
        _translate = QtCore.QCoreApplication.translate
        MiltiDB.setWindowTitle(_translate("MiltiDB", "MainWindow"))
        self.labelQueryEditor.setText(_translate("MiltiDB", "Редактор запросов"))
        self.runQuery.setText(_translate("MiltiDB", "Run"))
        self.saveResult.setText(_translate("MiltiDB", "Сохранить результат"))
        self.labelLogInfo.setText(_translate("MiltiDB", "Информация"))
        self.labelQueryResult.setText(_translate("MiltiDB", "Часть результата запроса"))
